drop database if exists dbPeliculas;
create database dbPeliculas;
use dbPeliculas;

create table pelicula(
id int not null auto_increment primary key,
titulo varchar(100) not null,
director varchar(100) not null,
anio_estreno year not null,
genero varchar(30) not null,
duracion decimal(5,2) not null,
calificacion int,
imagen varchar(500) null
);

INSERT INTO pelicula (titulo, director, anio_estreno, genero, duracion, calificacion, imagen) VALUES
('El Padrino', 'Francis Ford Coppola', 1972, 'Drama', 175.00, 9, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Pulp Fiction', 'Quentin Tarantino', 1994, 'Crimen', 154.00, 9, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('El Caballero de la Noche', 'Christopher Nolan', 2008, 'Acción', 152.00, 9, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('Forrest Gump', 'Robert Zemeckis', 1994, 'Drama', 142.00, 8, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Origen', 'Christopher Nolan', 2010, 'Ciencia Ficción', 148.00, 8, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('Matrix', 'Lana Wachowski', 1999, 'Ciencia Ficción', 136.00, 8, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Titanic', 'James Cameron', 1997, 'Romance', 194.00, 8, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Parásitos', 'Bong Joon-ho', 2019, 'Drama', 132.00, 9, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('Gladiador', 'Ridley Scott', 2000, 'Acción', 155.00, 8, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Interestelar', 'Christopher Nolan', 2014, 'Ciencia Ficción', 169.00, 9, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('El Silencio de los Inocentes', 'Jonathan Demme', 1991, 'Thriller', 118.00, 8, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('La Lista de Schindler', 'Steven Spielberg', 1993, 'Drama', 195.00, 9, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Bastardos sin Gloria', 'Quentin Tarantino', 2009, 'Bélico', 153.00, 8, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('El Gran Hotel Budapest', 'Wes Anderson', 2014, 'Comedia', 100.00, 8, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Django sin Cadenas', 'Quentin Tarantino', 2012, 'Western', 165.00, 8, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('El Club de la Pelea', 'David Fincher', 1999, 'Drama', 139.00, 9, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('La La Land', 'Damien Chazelle', 2016, 'Musical', 128.00, 8, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('El Laberinto del Fauno', 'Guillermo del Toro', 2006, 'Fantasía', 118.00, 8, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('Scarface', 'Brian De Palma', 1983, 'Crimen', 170.00, 8, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Whiplash', 'Damien Chazelle', 2014, 'Drama', 107.00, 8, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('Cadena Perpetua', 'Frank Darabont', 1994, 'Drama', 142.00, 9, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('El Padrino II', 'Francis Ford Coppola', 1974, 'Drama', 202.00, 9, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('12 Hombres sin Piedad', 'Sidney Lumet', 1957, 'Drama', 96.00, 9, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('El Señor de los Anillos: La Comunidad del Anillo', 'Peter Jackson', 2001, 'Fantasía', 178.00, 9, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('El Señor de los Anillos: Las Dos Torres', 'Peter Jackson', 2002, 'Fantasía', 179.00, 9, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('El Señor de los Anillos: El Retorno del Rey', 'Peter Jackson', 2003, 'Fantasía', 201.00, 9, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Harry Potter y la Piedra Filosofal', 'Chris Columbus', 2001, 'Fantasía', 152.00, 8, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Harry Potter y las Reliquias de la Muerte - Parte 2', 'David Yates', 2011, 'Fantasía', 130.00, 8, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('E.T. el Extraterrestre', 'Steven Spielberg', 1982, 'Ciencia Ficción', 115.00, 8, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Jurassic Park', 'Steven Spielberg', 1993, 'Aventura', 127.00, 8, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('Indiana Jones: En Busca del Arca Perdida', 'Steven Spielberg', 1981, 'Aventura', 115.00, 8, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Regreso al Futuro', 'Robert Zemeckis', 1985, 'Ciencia Ficción', 116.00, 8, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Terminator 2: El Juicio Final', 'James Cameron', 1991, 'Acción', 137.00, 8, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('Aliens: El Regreso', 'James Cameron', 1986, 'Ciencia Ficción', 137.00, 8, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Rocky', 'John G. Avildsen', 1976, 'Deporte', 120.00, 8, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('Karate Kid', 'John G. Avildsen', 1984, 'Deporte', 126.00, 7, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Top Gun', 'Tony Scott', 1986, 'Acción', 110.00, 7, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Misión Imposible', 'Brian De Palma', 1996, 'Acción', 110.00, 7, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('Soy Leyenda', 'Francis Lawrence', 2007, 'Ciencia Ficción', 101.00, 7, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Yo, Robot', 'Alex Proyas', 2004, 'Ciencia Ficción', 115.00, 7, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('El Discurso del Rey', 'Tom Hooper', 2010, 'Drama', 118.00, 8, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Belleza Americana', 'Sam Mendes', 1999, 'Drama', 122.00, 8, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Million Dollar Baby', 'Clint Eastwood', 2004, 'Drama', 132.00, 8, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('Sin Perdón', 'Clint Eastwood', 1992, 'Western', 130.00, 8, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Bailando con Lobos', 'Kevin Costner', 1990, 'Western', 181.00, 8, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('Los Siete Samuráis', 'Akira Kurosawa', 1954, 'Acción', 207.00, 9, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('El Séptimo Sello', 'Ingmar Bergman', 1957, 'Drama', 96.00, 8, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Amélie', 'Jean-Pierre Jeunet', 2001, 'Comedia', 122.00, 8, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('La Vida es Bella', 'Roberto Benigni', 1997, 'Drama', 116.00, 9, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Coco', 'Lee Unkrich', 2017, 'Animación', 105.00, 8, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('Buscando a Nemo', 'Andrew Stanton', 2003, 'Animación', 100.00, 8, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Cincuenta Sombras de Grey', 'Sam Taylor-Johnson', 2015, 'Romance', 125.00, 5, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Batman v Superman: El Amanecer de la Justicia', 'Zack Snyder', 2016, 'Acción', 151.00, 6, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('Crepúsculo', 'Catherine Hardwicke', 2008, 'Romance', 122.00, 5, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Scooby-Doo', 'Raja Gosnell', 2002, 'Comedia', 86.00, 5, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('After: Aquí empieza todo', 'Jenny Gage', 2019, 'Romance', 106.00, 5, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('La Momia', 'Alex Kurtzman', 2017, 'Aventura', 110.00, 5, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Gato con Botas: El último deseo', 'Joel Crawford', 2022, 'Animación', 102.00, 7, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('Sonic the Hedgehog', 'Jeff Fowler', 2020, 'Aventura', 99.00, 7, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Un lugar tranquilo', 'John Krasinski', 2018, 'Terror', 90.00, 7, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('It', 'Andrés Muschietti', 2017, 'Terror', 135.00, 7, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Escuadrón Suicida', 'David Ayer', 2016, 'Acción', 123.00, 5, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Garra', 'Jeremiah Zagar', 2022, 'Comedia', 117.00, 7, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('El contador', 'Gavin O Connor', 2016, 'Acción', 128.00, 7, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Infiltrado en el KKKlan', 'Spike Lee', 2018, 'Comedia', 135.00, 7, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('Un pequeño favor', 'Paul Feig', 2018, 'Suspenso', 117.00, 7, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Animales fantásticos y dónde encontrarlos', 'David Yates', 2016, 'Fantasía', 133.00, 7, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Jurassic World: El reino caído', 'J.A. Bayona', 2018, 'Aventura', 128.00, 6, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('Venom', 'Ruben Fleischer', 2018, 'Acción', 112.00, 6, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Ocean''s 8', 'Gary Ross', 2018, 'Comedia', 110.00, 6, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('Mamma Mia! Una y otra vez', 'Ol Parker', 2018, 'Musical', 114.00, 6, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Holmes & Watson', 'Etan Cohen', 2018, 'Comedia', 90.00, 4, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('El cascanueces y los cuatro reinos', 'Lasse Hallström', 2018, 'Fantasía', 99.00, 5, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('Robin Hood', 'Otto Bathurst', 2018, 'Aventura', 116.00, 5, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Mortal Engines', 'Christian Rivers', 2018, 'Ciencia Ficción', 128.00, 6, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('Alita: Ángel de combate', 'Robert Rodriguez', 2019, 'Ciencia Ficción', 122.00, 7, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Hellboy', 'Neil Marshall', 2019, 'Acción', 120.00, 5, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Men in Black: International', 'F. Gary Gray', 2019, 'Ciencia Ficción', 114.00, 5, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('X-Men: Fénix Oscura', 'Simon Kinberg', 2019, 'Acción', 113.00, 5, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Godzilla II: Rey de los monstruos', 'Michael Dougherty', 2019, 'Acción', 132.00, 6, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('Terminator: Destino oscuro', 'Tim Miller', 2019, 'Ciencia Ficción', 128.00, 6, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Disaster Movie', 'Jason Friedberg', 2008, 'Comedia', 90.00, 2, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Jack y su gemela', 'Dennis Dugan', 2011, 'Comedia', 116.00, 3, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('Catwoman', 'Pitof', 2004, 'Acción', 104.00, 3, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Ballistic: Ecks vs. Sever', 'Wych Kaosayananda', 2002, 'Acción', 91.00, 2, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('Superbabies: Baby Geniuses 2', 'Bob Clark', 2004, 'Comedia', 88.00, 2, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('The Room', 'Tommy Wiseau', 2003, 'Drama', 99.00, 3, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Manos: The Hands of Fate', 'Harold P. Warren', 1966, 'Terror', 74.00, 2, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('Battlefield Earth', 'Roger Christian', 2000, 'Ciencia Ficción', 118.00, 2, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Gigli', 'Martin Brest', 2003, 'Comedia', 121.00, 2, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg'),
('Crepúsculo: Luna Nueva', 'Chris Weitz', 2009, 'Romance', 130.00, 4, 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWEwMzctOTcwYmY2YmExZjg2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Transformers: El último caballero', 'Michael Bay', 2017, 'Acción', 154.00, 4, 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTItNDRjYy00NWQwLWI1M2MtNDBiY2ZhNTc0ZDEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
('Cincuenta sombras más oscuras', 'James Foley', 2017, 'Romance', 118.00, 4, 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg'),
('El último airbender', 'M. Night Shyamalan', 2010, 'Fantasía', 103.00, 3, 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
('Pixels', 'Chris Columbus', 2015, 'Ciencia Ficción', 105.00, 4, 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg'),
('Sex and the City 2', 'Michael Patrick King', 2010, 'Comedia', 146.00, 3, 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('La liga de la justicia', 'Zack Snyder', 2017, 'Acción', 120.00, 4, 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDPhMWUyMy00YWZkLWE1MjItNDlmMTQxMTk0NDk2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Fantastic Four', 'Josh Trank', 2015, 'Acción', 100.00, 3, 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg'),
('Emoji: La película', 'Tony Leondis', 2017, 'Animación', 86.00, 2, 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MThiLTg4Y2UtNDgwZjIxMTEyMDFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg'),
('Gotti', 'Kevin Connolly', 2018, 'Crimen', 112.00, 3, 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDItN2IyIG00YjI1LTliYjItODZhOWI1ZDUxNjU0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg');